### ISSUE TITLE
Console[3221]: setPresentationOptions called with NSApplicationPresentationFullScreen when there is no visible fullscreen window

### ISSUE THREAD

**Issue by webhat** [firstlook/autocanary#10] opened 2015-05-28 13:49 UTC
I just tried the OSX package from (here)[https://firstlook.org/code/project/autocanary/]. It installs fine. However, when I run it I see this pop-up:

![blank_skitch_document](https://cloud.githubusercontent.com/assets/164971/7861540/060c718a-0551-11e5-972a-9c063b64ebeb.png)

And get the following message in Console.app

```
   Console[3221]: setPresentationOptions called with NSApplicationPresentationFullScreen when there is no visible fullscreen window; this call will be ignored.
```

**Comment by YourMomsAndMe** [comment] 2015-05-28 14:01
Hey @webhat can you add some additional information: OS and Build

**Comment by webhat** [comment] 2015-05-28 14:08
OSX: 10.9.5 Where do I get build from?

**Comment by webhat** [comment] 2015-05-28 14:08
Unless you are auto delivering, it is the current build.

**Comment by YourMomsAndMe** [comment] 2015-05-28 14:18
Go to  / About this Mac... / 
Then on the "version" (the word itself), click it and it should reveal the build. 

This could help the developers in trying to recreate the issue at hand. Currently I'm running 10.10.3 (build 14D136). (The build isn't as important as the OS but can help in trying to be very specific, for example, the issue isn't being seen on just a 10.9.5 install).

**Comment by webhat** [comment] 2015-05-28 14:40
I didn't realize you meant my build number, I thought you meant the package I downloaded

Build: 13F1077

**Comment by YourMomsAndMe** [comment] 2015-05-28 20:58
@webhat Just looking into to this while we wait for the developers. 
Finally got myself a MBP with 10.9.3 Build 13D65 (left it w. an early build in case I can recreate the issue). It installed and executed fine. 
But looking at Console I notice it tends to let me know when it's AutoCanary that's leaving a note. If possible, can you:
• Quit AutoCanary (and all other apps if possible)
• Open Console, Insert Marker
• Then try to launch AutoCanary and note the errors -- unless they are the same.

In the meantime, I'm going to update to 10.9.5 to see if I can recreate the issue.

**Comment by YourMomsAndMe** [comment] 2015-05-28 21:38
@webhat Couldn't recreate it on 10.9.5 Build 13F1077 
This is how Console is showing me the info (just in case you see more info specifically from AutoCanary)
![screen shot 2015-05-28 at 5 25 56 pm](https://cloud.githubusercontent.com/assets/12644055/7871609/fab99548-055e-11e5-8225-9093c095c0de.png)

If any other details, please add. I'll keep playing with it on my end.

**Comment by webhat** [comment] 2015-05-29 08:32
@SevenTrainCreator Inspired by your screen shot I went back in my console log and saw this, which looks much more relevant:

>  28/05/15 13:17:54,212 AutoCanary[3212]: Traceback (most recent call last):
> 28/05/15 13:17:54,212 AutoCanary[3212]:   File "/Applications/AutoCanary.app/Contents/Resources/**boot**.py", line 351, in <module>
> 28/05/15 13:17:54,212 AutoCanary[3212]:     _run()
> 28/05/15 13:17:54,213 AutoCanary[3212]:   File "/Applications/AutoCanary.app/Contents/Resources/__boot__.py", line 336, in _run
> 28/05/15 13:17:54,213 AutoCanary[3212]:     exec(compile(source, path, 'exec'), globals(), globals())
> 28/05/15 13:17:54,213 AutoCanary[3212]:   File "/Applications/AutoCanary.app/Contents/Resources/autocanary.py", line 2, in <module>
> 28/05/15 13:17:54,213 AutoCanary[3212]:     autocanary.main()
> 28/05/15 13:17:54,213 AutoCanary[3212]:   File "autocanary/autocanary.pyc", line 362, in main
> 28/05/15 13:17:54,213 AutoCanary[3212]:   File "autocanary/gnupg.pyc", line 68, in seckeys_list
> 28/05/15 13:17:54,213 AutoCanary[3212]: IndexError: list index out of range
> 28/05/15 13:17:54,234 AutoCanary[3212]: AutoCanary Error
> 28/05/15 13:17:54,234 AutoCanary[3212]: 2015-05-28 13:17:54.233 AutoCanary[3212:707] AutoCanary Error
> 28/05/15 13:17:57,882 com.apple.launchd.peruser.501[262]: (org.pythonmac.unspecified.AutoCanary.106336[3212]) Exited with code: 255

**Comment by YourMomsAndMe** [comment] 2015-05-29 13:01
@webhat This is great (*information; that is). 
It reads like a similar issue noted for 10.8.5.
May I ask what kind of encryption set up you have. Meaning, are you using GPGTools. 
Again, this is information gathering to see if it helps.
Take a look here: https://github.com/firstlook/autocanary/issues/6

**Comment by webhat** [comment] 2015-05-29 13:09
I have gpg 1 and 2 on the command line installed with macports, other than that I have nothing.

**Comment by micahflee** [comment] 2015-06-02 00:40
It looks like this is a duplicate of #6, related to a crash at `File "autocanary/gnupg.pyc", line 68, in seckeys_list` because of running gpg1 instead of gpg2.

**Closed as completed** 2015-06-02 00:40 UTC
Labels: bug, duplicate
